spring.application.name=senpai-anime

server.port=8081

spring.web.resources.static-locations=file:subtitles/
spring.web.resources.add-mappings=true
spring.mvc.static-path-pattern=/**

logging.level.org.springframework.web.context.request.async=ERROR
logging.level.bg.senpai.anime=DEBUG

