spring.application.name=senpai-anime

server.port=${SERVER_PORT}

spring.web.resources.static-locations=file:subtitles/
spring.web.resources.add-mappings=true
spring.mvc.static-path-pattern=/**

logging.level.org.springframework.web.context.request.async=ERROR
logging.level.bg.senpai.anime=DEBUG

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

